[package]
name = "git-wasp"
version = "0.1.0"
description = "Git Wasp — a Git desktop client. Branch fast. Merge clean. Don't get stung."
authors = []
edition = "2021"

[lib]
name = "git_wasp_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-window-state = "2"
git2 = { version = "0.20", features = ["vendored-libgit2", "vendored-openssl"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
notify = "8"
dirs = "5"
anyhow = "1"
thiserror = "2"
log = "0.4"
keyring = { version = "3", features = ["apple-native", "windows-native", "linux-native-sync-persistent", "crypto-rust"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
md5 = "0.7"
base64 = "0.22"
tauri-plugin-log = "2.8.0"
notify-debouncer-full = "0.7.0"
tempfile = "3"

[features]
ci = []

[dev-dependencies]
tauri = { version = "2", features = ["test"] }
httpmock = "0.8"

[env]
# workaround needed to prevent `STATUS_ENTRYPOINT_NOT_FOUND` error in tests
# see https://github.com/tauri-apps/tauri/pull/4383#issuecomment-1212221864
__TAURI_WORKSPACE__ = "true"
